puppetlabs/gettext-setup-gem

lib/tasks/gettext.rake
This change to the rake task (gettext:pot) removes the '#: FILE:LINE'
comments from the generated .pot file. The intent is to reduce churn
when the .pot file is under source control.
=> Remove location comments from generated .pot file

gettext-setup.gemspec
this breaks Debian testing at the moment: https://ci.debian.net/data/packages/unstable/amd64/r/ruby-gettext-setup/20160913_095630.autopkgtest.log.gz
```
Invalid gemspec in [gettext-setup.gemspec]: No such file or directory - git
```
=> use Ruby Dir globbing instead of git ls-files

lib/gettext-setup/gettext_setup.rb
The fast_gettext gem which this library wraps supports multiple formats
for translation files. This commit allows the user to specify which
format to use for loading translations. This is needed to give us
flexibility to choose whether to use .mo binary files (more overhead,
but parallels the process for other languages) or read directly from .po
files.
=> Refactor the initialize method to allow different file formats

lib/tasks/gettext.rake
This commit allows the user to add an `exclude_files` field to the
config file, which contains a list of file paths to be excluded from
the files specified with the `source_files` option.
=> (INTL-8) Add a config option to exclude certain files from translation

Gemfile.lock, README.md, gettext-setup.gemspec, lib/gettext-setup/gettext_setup.rb, lib/tasks/gettext.rake, locales/config-sample.yaml
When no argument is passed to rxgettext's `--add-comments` flag, all
comments are extracted. We want to be able to restrict this to just
comments made for translators, so we allow the user to supply a tag
using a new `comments_tag` config in the config.yaml. This tag will
default to "TRANSLATORS" if not supplied. If supplied but empty,
all comments will be extracted, affording us backwards-compatibility.
Fixes https://tickets.puppetlabs.com/browse/INTL-9
=> Allow restriction of extracted comments

lib/tasks/gettext.rake
Previously the update_pot rake task only replaced the POT file when
strings were added or changed, but not when they were deleted. This
commit updates the comparison logic to account for the warnings issued
by msgcmp when strings have been deleted, and act on them to replace the
POT file.
=> (INTL-13) Make update_pot task also replace POT when strings are deleted

lib/tasks/gettext.rake
In modules, we would like the globs to be a little more flexible so we can set the source_files across all the modules instead of tailoring each one. This addition goes through the final translatable file list and removes directories, which cause rxgettext to error out if encountered.
```shell
Error parsing lib/puppet/type/acl
/Users/eric.putnam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/parser/glade.rb:27:in `readlines': Is a directory @ io_fillbuf - fd:7 lib/puppet/type/acl (Errno::EISDIR)
from /Users/eric.putnam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/parser/glade.rb:27:in `target?'
from /Users/eric.putnam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:361:in `block in …
```
=> (INTL-14) do not send directories to rxgettext

lib/gettext-setup/gettext_setup.rb, spec/fixtures/alt_locales/alt_locales.pot, spec/fixtures/alt_locales/config.yaml, spec/fixtures/alt_locales/jp/alt_locales.po, spec/lib/gettext_setup_spec.rb
Currently, available_locales is being overwritten every time a module is initialized with GettextSetup, so if we want a German translation, it is only be available if it is available in the most recent module that has been initialized (alphabetical order). This commit moves FastGettext.default_available locales to be initialized outside of the GettextSetup initialization and subsequently added to using a join every time a new project is processed by GettextSetup. This allows us to have a 'master' list of locales to choose from, which will contain all locales from all projects, instead of relying on the last initialized project to contain all the locales we might need. Spec tests include testing that a list is built when more than one project is initialized and that locales from that list …
=> (INTL-18) default_available_locales as global variable

gettext-setup.gemspec
Since the fast_gettext version we use does not work with Ruby < 1.9.0, we
should add this dependency.
=> (maint) Add minimum required ruby version

lib/tasks/gettext.rake
If `msgcmp` is not installed on a system, the task should still complete and
the POT should still be updated.
=> (INTL-19) Allow `update_pot` when `msgcmp` is not installed

lib/gettext-setup/gettext_setup.rb, spec/lib/gettext_setup_spec.rb
Instead of using individual text_domains, we will now be using a 'chain' which allows the continued use of \_() instead of switching to d\_() or D\_(). A chain will aggregate all the text domains into one master text domain so that we will no longer need to switch domains to find a translation.
=> (INTL-17) Implement text_domain chaining

gettext-setup.gemspec, lib/gettext-setup/gettext_setup.rb, spec/lib/gettext_setup_spec.rb
Locales are placed in preference order. If the `q` values are equal, past
behavior chose the last language in the header string, which will usually be
the default locale.
If `q` values are equal, the `negotiate_locale` method should choose the first
value in the list.
=> (INTL-20) Use first choice when negotiating locale

lib/tasks/gettext.rake, lib/tasks/task_helper.rb, spec/fixtures/pot_update/add.pot, spec/fixtures/pot_update/change.pot, spec/fixtures/pot_update/non_string_changes.pot, spec/fixtures/pot_update/old.pot, spec/fixtures/pot_update/remove.pot, spec/lib/gettext_setup_spec.rb, spec/spec_helper.rb, spec/tasks/update_pot_spec.rb
The first commit adds an additional regex to the update_pot rake task, which
checks for the warning issued by `msgcmp` when it sees strings in the
new POT file which were not present in the old one. Previously it was
assumed `msgcmp` exited 1 in this case, but it does not, so the
additional grepping of stderr is necessary to detect string additions.
The second commit adds tests to make sure we can properly detect all the
different kinds (and absence) of POT file string changes. In order to
facilitate this testing, the helper methods around the `gettext` rake
tasks have been moved into their own file. Note that these new tests
are skipped if msgcmp is not present on the system.
=> (INTL-25) ensure update_pot rake task detects string additions

.rubocop.yml, lib/generate_metadata_pot.rb, lib/metadata_pot/metadata_pot.rb, lib/tasks/gettext.rake
Using Ruby to generate a POT file for metadata.json. This also creates a rake task to generate the POT file. This will allow us to automate keeping the metadata.json POT file up to date.
This has been tested on tagmail and accounts.
=> WIP - (MODULES-4640) - Generate metadata POT file and Rake Task

.gitignore, lib/gettext-setup/pot.rb, lib/tasks/gettext.rake, spec/lib/gettext-setup/gettext_setup_spec.rb, spec/lib/gettext-setup/metadata_pot_spec.rb, spec/lib/gettext-setup/pot_spec.rb, spec/lib/tasks/gettext_rake_spec.rb, spec/spec_helper.rb
Although the rake tasks would print out error messages indicating failure, the
tasks would still exit with status 0, meaning they wouldn't get proper
attention.
Fixes https://tickets.puppetlabs.com/browse/INTL-27
=> Exit with status 1 when rake tasks fail

spec/lib/gettext-setup/metadata_pot_spec.rb, spec/lib/gettext-setup/pot_spec.rb
Specs depend on Dir.mktmpdir for a few working directories, so the
stdlib file providing it should be required. Currently it's loaded only
as part of Bundler's own initialisation.
=> (maint) Require stdlib "tmpdir" providing Dir.mktmpdir

gettext-setup.gemspec
They appear to be leftovers from a sample Sinatra project, not used in
the current gem test suite.
=> (maint) Remove unused rack-test, webmock dependencies

lib/gettext-setup/gettext_setup.rb, spec/lib/gettext-setup/gettext_setup_spec.rb
When the Accept header contains something like 'de-DE', and we have 'en'
and 'de' available, we used to only look for a 'de-DE' message catalog, but
not for the more general 'de' catalog.
This patch makes it so that we drop country variant before looking for a
message catalog, i.e., we treat 'de-DE' and 'de' as exactly the same. This
will work as long as we do not need to have both a message catalog for the
language and one for that language respecting a variant.
Fixes https://tickets.puppetlabs.com/browse/ENTERPRISE-1060
=> When negotiating locale, only consider language, but not country variant

lib/gettext-setup/pot.rb
Set the language variable from ENV['LANGUAGE'] before the variable
is used as an argument for the po_file_path method.
=> Fix ordering of language var assignment from env

lib/gettext-setup/gettext_setup.rb
FastGettext prefers the first item in its list of available locales when
choosing a locale before it has been set by the user. However, we were
putting our defaults at the end of the list we use to initialize
FastGettext, meaning FastGettext was choosing an essentially random
locale as its initial value for `locale`. This commit updates the way we
construct our `available_locales` list to put the defaults first.
=> (PUP-7881) Put default locales at the front of available_locales

lib/gettext-setup/pot.rb
When the Ruby POT file is moved, it doesn't exist in the repo when merging POT files. Copying means that it exists in the new location and also the Ruby strings are contained in the merged file.
=> (FM-6323) - Copying Ruby POT rather than moving it

gettext-setup.gemspec, lib/gettext-setup/gettext_setup.rb, lib/gettext-setup/metadata_pot.rb, lib/gettext-setup/pot.rb, lib/tasks/gettext.rake, spec/lib/gettext-setup/gettext_setup_spec.rb, spec/lib/gettext-setup/pot_spec.rb
for the sake of consistency across POT files (ruby, puppet, metadata), it seems to make sense for the headers to all be created in one place. This change allows for the creation of 'blank' POT files, or POT files with only a header, by passing in a blank input file. This provides the following benefits:
- When POT files are merged, differences in header content can cause a lot of clutter in the final POT file. identical headers will cut down on this clutter substantially.
- The generate function can be used to create blank POT files to allow for the appending of POT files for other languages in the future
- Consistency is great
- GettextSetup knows a lot about the current project so it can provide header info that other libraries may not be able to, like project name, etc.
=> (FM-6415) create header_only option for pot generation

lib/gettext-setup/gettext_setup.rb, lib/gettext-setup/pot.rb
Prior to this commit the Gettext:Pot module would setup the FastGettext
config and runtime. This would cause strange conflicts with other calls
to FastGettext (for example, when calling the rake task in an
environment that also contains Puppet 5.3.3) so we decided that
since the rake tasks do not require the FastGettext runtime config,
they should not try to set it up.
This commit refactors the GettextSetup.initialize method to call out
to a GettextSetup.initialize_config method, that only configures the
file-related info for the library. Then the GettextSetup:Pot module
is updated to call the GettextSetup.initialized_config method instead
of initialize. As far as I know, the GettextSetup:Pot module is only
called by the rake tasks so hopefully this is a safe fix.
=> (INTL-31) Refactor rake tasks to not setup FastGettext runtime

.rubocop.yml
With this absent, Rubocop appears to assume the version running the
test is the minimum ruby version, which is in conflict with what is
defined in the gemspec.
=> (maint) Fix Travis' TargetRubyVersion

lib/gettext-setup/gettext_setup.rb, spec/lib/gettext-setup/gettext_setup_spec.rb
Previously, if GettextSetup.initialize was called with a config.yaml, but
there were no corresponding language subdirectories, e.g. locales/ja,
then GettextSetup would set FastGettext.default_locale to nil.
The issue was because GettextSetup set FastGettext.default_available_locales
to an empty array in commit bc57b9a. However, FastGettext interpreted that
to mean there were no available locales! So later attempts to set the
FastGettext.default_locale were "filtered out", since the argument was
never one of the available locales.
One subtle issue here was that FastGettext.default_available_locales
defaults to nil. So Array union (`|`), could produce surprising results
the first time the Gettext.initialize method was called:
$ ruby -e "puts nil | []"
true
This commit removes the call to …
=> (GH-61) Handle initial nil value

.rubocop.yml, spec/lib/gettext-setup/gettext_setup_spec.rb
Fixes: https://github.com/puppetlabs/gettext-setup-gem/issues/64
Patch from Hleb Valoshka for Debian
https://lists.debian.org/debian-ruby/2018/04/msg00034.html
https://bugs.debian.org/894829
=> spec: fix invalid byte-sequence in US-ASCII with ruby2.5 (GH-64)

lib/gettext-setup/pot.rb
If msgcamp isn't on the system, we were previously relying on the system
throwing an IOError that we could catch. Unfortunately, this wasn't
consistently happening. This commit adds an additional check to
explicitly print out a warning if msgpack is not available and to
proceed with replacing the old pot with the new one.
=> (maint) Use new pot if msgcmp unavailable

lib/gettext-setup/metadata_pot.rb
Fixes the following error for Ruby 2.6:
```
uninitialized constant GettextSetup::MetadataPot::DateTime
```
=> Add `date` require to metadata_pot.rb

.travis.yml, gettext-setup.gemspec, lib/gettext-setup/gettext_setup.rb
It's currently impossible to install dependencies with `bundle
install..` on a modern distribution. bundler 2 is available since more
than a year.
=> Don't depend on a legacy bundler release

gettext-setup.gemspec
gettext 3.3.0 has dropped support for < ruby v2.5. This commit
constrains the version of gettext to < than that y version.
=> (maint) contrain gettext version to < 3.3.0

.rubocop.yml, lib/gettext-setup/gettext_setup.rb
A simple rubocop fix caused an error in older versions of ruby. This fix
uses the original `send` command instead.
=> (maint) Revert error for some versions of ruby

CODEOWNERS
Prior to this commit the ownership of the repo is the razor team. As this team is no longer an entity, this PR is to update the ownership so that the team can start merging PRs.
=> (maint) Update CODEOWNERS to include devx
